version: "3.9"

services:
  swagger:
    image: redocly/redoc
    ports:
      - 8083:80      
    environment:
      - PAGE_TITLE=Types
      - SPEC_URL=swagger/openapi.yml
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
