openapi: "3.0.0"
info:
  version: 1.0.0
  title: Integration Utils
tags:
- name: models
  x-displayName: All Models
  description: |
    ## Product
    <SchemaDefinition schemaRef="#/components/schemas/Product" />
    
    ## Money
    <SchemaDefinition schemaRef="#/components/schemas/Money" />     
    
    ## Script
    <SchemaDefinition schemaRef="#/components/schemas/Script" />     
components:
  schemas:
    Product:
      type: object
      properties:
        createdAt: { type: string, format: date-time }
        description: { type: string }
        id: { type: integer}
        imageURL: { type: string }
        price:
          $ref: '#/components/schemas/Money'
        title: { type: string }
        updatedAt: { type: string, format: date-time }
        url: {type: string }
    Money:
      type: object
      properties:
        value:
          type: number
          example: 56.2
        currencyCode:
          type: string
          example: EUR
    Script:
      type: object
      properties:
        name:
          type: string
          example: Name
        description:
          type: string
          example: Description
        src:
          type: string
          example: https://cdn.commoninja.com/sdk/latest/commonninja.js
        location:
          type: string
          example: head
        loadMethod:
          type: string
          example: defer
        scope:
          type: string
          example: all
        cache:
          type: boolean
          example: true
        